# Generated by Django 4.0.2 on 2022-02-24 12:10

import django.core.validators
from django.db import migrations, models
import online_library.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), online_library.web.models.isalpha_validation])),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField()),
                ('type', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), online_library.web.models.isalpha_validation])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), online_library.web.models.isalpha_validation])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), online_library.web.models.isalpha_validation])),
                ('image_url', models.URLField()),
            ],
        ),
    ]
