# Generated by Django 4.0.2 on 2022-02-20 16:04

import django.core.validators
from django.db import migrations, models
import exams.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), exams.web.models.valid_only_character])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), exams.web.models.valid_only_character])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', validators=[exams.web.models.MaxSizeInMbValidator(5)])),
            ],
        ),
    ]
