# Generated by Django 4.0.2 on 2022-02-25 12:59

import Recipes.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), Recipes.web.models.get_valid_character])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
