# Generated by Django 4.0.2 on 2022-02-25 14:31

import Recipes.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default=11, max_length=30, validators=[django.core.validators.MinLengthValidator(2), Recipes.web.models.get_valid_character]),
            preserve_default=False,
        ),
    ]
