# Generated by Django 4.0.2 on 2022-02-23 14:40

import django.core.validators
from django.db import migrations, models
import test_exam.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), test_exam.web.models.get_valid_character])),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), test_exam.web.models.get_valid_character])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), test_exam.web.models.get_valid_character])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image_url', models.URLField()),
            ],
        ),
    ]
