# Generated by Django 4.0.2 on 2022-02-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
