# Generated by Django 4.0.2 on 2022-02-26 17:27

import Exam_preparation.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[Exam_preparation.web.models.get_value_only_character])),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), Exam_preparation.web.models.get_value_only_character])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), Exam_preparation.web.models.get_value_only_character])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, default='/static_files/images/user.png', null=True, upload_to='', validators=[Exam_preparation.web.models.MaxSizeInMbValidator(5.0)])),
            ],
        ),
    ]
