# Generated by Django 4.0.1 on 2022-01-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='egn',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
