# Generated by Django 4.0.1 on 2022-01-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_employee_egn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Software developer'), (2, 'Qa')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='egn',
            field=models.IntegerField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
