# Generated by Django 4.0.1 on 2022-01-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_employee_job_title_alter_employee_egn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='companies',
            field=models.CharField(choices=[('Google', 'Google'), ('Facebook', 'Facebook')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
