# Generated by Django 4.0.1 on 2022-01-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_employee_firms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='companies',
            field=models.CharField(choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Softuni', 'Softuni')], max_length=8),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
    ]
