# Generated by Django 4.0.1 on 2022-01-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_employee_firms_alter_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Software developer'), (2, 'Qa')]),
        ),
    ]
