# Generated by Django 4.0.1 on 2022-01-31 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('employees', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.employee')),
            ],
        ),
    ]
