# Generated by Django 4.0.1 on 2022-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_remove_user_id_alter_user_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Ministerstvo Migracii', 'Ministerstvo Migracii')], max_length=21),
        ),
        migrations.AlterField(
            model_name='employee',
            name='egn',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='EGN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, default='NO NAME', max_length=30, null=True),
        ),
    ]
