# Generated by Django 4.0.1 on 2022-02-11 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='egn',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(10)], verbose_name='EGN'),
        ),
    ]
