# Generated by Django 4.0.1 on 2022-02-13 16:33

import Employees.application.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_alter_employee_egn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[Employees.application.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='egn',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='EGN'),
        ),
    ]
